cw22_root_path: C:\\Users\\victus\\output_root_2
seed_docs_file: seed.txt
output_dir: crawl_results/seed_500_crawl_10000_dclm_fasttext_big
num_selected_docs_per_iter: 500
num_workers: 50
save_state_every: -1
max_num_docs: 10000
selection_method: dclm_fasttext_score
order: desc
wandb: true
wandb_project: crawler
wandb_run_name: seed_10k_crawl_20m_dclm_fasttext
rating_methods:
  - type: length
  - type: fasttext_score
    rater_name: dclm_fasttext_score
    model_path: fasttext_scorers/openhermes_reddit_eli5_vs_rw_v2_bigram_200k_train.bin
plots:
  - length
  - dclm_fasttext_score
